%YAML 1.2
%TAG ! tag:fawkesrobotics.org,cfg/
---
# Configuration meta information document
include:
  # reads files ending in .yaml from conf.d config subdir
  # - !ignore-missing conf.d/
  # Reads the host-specific configuration file, no failure if missing
  - !host-specific host.yaml
---
# Main configuration document

llsfrb:
  log:
    level: info
    general: refbox.log
    clips: clips.log
    game: game.log

  mps:
    enable: true
    # type: 1(incoming station), 2(singel p&p), 3(double p&p), 4(delivery station)
    stations:
      C-BS:
        active: true
        type: BS
        host: !ipv4 192.168.2.27
        port: !tcp-port 4840
        connection: mockup
      C-CS1:
        active: true
        host: !ipv4 192.168.2.24
        port: !tcp-port 4840
        type: CS
        connection: mockup
      C-CS2:
        active: true
        host: !ipv4 192.168.2.25
        port: !tcp-port 4840
        type: CS
        connection: mockup
      C-RS1:
        active: true
        host: !ipv4 192.168.2.23
        port: !tcp-port 4840
        type: RS
        connection: mockup
      C-RS2:
        active: true
        host: !ipv4 192.168.2.26
        port: !tcp-port 4840
        type: RS
        connection: mockup
      C-DS:
        active: true
        host: !ipv4 192.168.2.28
        port: !tcp-port 4840
        type: DS
        connection: mockup
      M-BS:
        active: true
        host: !ipv4 192.168.2.33
        port: !tcp-port 4840
        type: BS
        connection: mockup
      M-CS1:
        active: true
        host: !ipv4 192.168.2.30
        port: !tcp-port 4840
        type: CS
        connection: mockup
      M-CS2:
        active: true
        host: !ipv4 192.168.2.32
        port: !tcp-port 4840
        type: CS  
        connection: mockup
      M-RS1:
        active: true
        host: !ipv4 192.168.2.31
        port: !tcp-port 4840
        type: RS
        connection: mockup
      M-RS2:
        active: true
        host: !ipv4 192.168.2.34
        port: !tcp-port 4840
        type: RS
        connection: mockup
      M-DS:
        active: true
        host: !ipv4 192.168.2.29
        port: !tcp-port 4840
        type: DS
        connection: mockup

  clips:
    # Timer interval, in milliseconds
    timer-interval: 40

    main: refbox
    debug: true
    # debug levels: 0 ~ none, 1 ~ minimal, 2 ~ more, 3 ~ maximum
    debug-level: 2
    unwatch-facts: [time, signal, gamestate]
    unwatch-rules: [retract-time,
                    game-update-gametime-points, game-update-last-time,
                    net-send-beacon, net-send-GameState, net-send-OrderInfo,
                    net-send-MachineInfo, net-send-RobotInfo,
                    exploration-send-MachineReportInfo, net-broadcast-MachineInfo,
                    net-send-VersionInfo]

  comm:
    protobuf-dirs: ["@SHAREDIR@/msgs"]

    server-port: !tcp-port 4444
    
    public-peer:
      #host: !ipv4 192.168.122.255
      host: !ipv4 127.0.0.1
      #port: !udp-port 4444
      send-port: !udp-port 4444
      recv-port: !udp-port 4445

    cyan-peer:
      #host: !ipv4 192.168.122.255
      host: !ipv4 127.0.0.1
      #port: !udp-port 4441
      send-port: !udp-port 4441
      recv-port: !udp-port 4446

    magenta-peer:
      #host: !ipv4 192.168.122.255
      host: !ipv4 127.0.0.1
      #port: !udp-port 4442
      send-port: !udp-port 4442
      recv-port: !udp-port 4447

  mongodb:
    enable: false
    hostport: localhost
    collections:
      text-log: llsfrb.log
      clips-log: llsfrb.clipslog
      protobuf: llsfrb.protobuf

  game:
    teams: [Carologistics]
    crypto-keys:
      Carologistics: randomkey
    # whenever a random field should be generated or not (e.g. used from mongodb)
    random-field: true

  shell:
    refbox-host: localhost
    refbox-port: 4444

  workpiece-tracking:
   enable: true
   fail-safe: true

  simulation:
    enable: false
    # synchronize refbox time with the time of a simulation 
    time-sync:
      enable: true
      # estimate time by using the last given simulation time speed
      # (helps reducing the amount of messages to send)
      estimate-time: true
